config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :bookmarks, only: [:destroy, :index]
  resources :subscribers, only: [:create, :new]
  resources :user_infos
  resources :publications
  resources :authors
  resources :carts
  resources :plans
  resources :addresses, only: [:new, :edit, :destroy]
  devise_for :users
  root to: 'books#home'
  resources :books do
    resources :carts
    resources :book_catalogs
    resources :bookmarks, only: [:create]
  end
  resources :carts do
    resources :orders, except: [:index, :show, :edit]
  end
  resources :orders, only: [:index, :show, :edit]
  resources :plans, only: [:index]

  post "/plans/:sub_plan_id/select_plan" => "plans#select_plan", as: 'select_plan'
  post "/plans/:sub_plan_id/change_plan" => "plans#change_plan", as: 'change_plan'
  # get "/books/:book_id/book_catalogs/new" => "book_catalogs#new", :as => 'new_book_catalog'
  # post "/books/:book_id/book_catalogs" =>	"book_catalogs#create", :as => 'create_book_catalog'
  post "/books/:id/check_pincode" => "books#check_pincode", as: 'check_pincode'
  get  "/" => "books#home", :as => 'home'
  get  "pages/:page" => "pages#show"

  delete "/cart_books/:id" => "carts#destroy_cart_book", as: 'destroy_cart_book'
  get "/checkout/:cart_id" => "orders#checkout", as: 'order_checkout'

  get "/shipping_address" => "orders#select_shipping_address", as: 'select_shipping_address'
  post "/order_summary" => "orders#summary", as: 'order_summary'
  post "/cancel_order/:id" => "orders#cancel", as: 'cancel_order'
  post "/order/:order_id/return_requests" => "return_requests#create", as: 'return_request'
end

app/views/shared/_bottom-header.html.erb
<!-- start header bottom  -->
<div class="aa-header-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="aa-header-bottom-area">
          <!-- logo  -->
          <div class="aa-logo">
            <!-- Text based logo -->
            <a href="index.html">
              <%= image_tag("kitabiworm.jpg", alt: "KitabiWorm Logo", class: "img-logo")%>
            </a>
            <!-- img based logo -->
            <!-- <a href="index.html"><img src="img/logo.jpg" alt="logo img"></a> -->
          </div>
          <!-- / logo  -->
          <!-- search box -->
          <div class="aa-search-box">
            <form action="">
              <input type="text" name="" id="" placeholder="Search here ex. 'Harry Potter and the cursed child.' ">
              <button type="submit"><span class="fa fa-search"></span></button>
            </form>
          </div>
          <!-- / search box -->
        </div>
      </div>
    </div>
  </div>
</div>
<!-- / header bottom  -->

app/views/shared/_footer.html.erb
<section id="aa-support">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="aa-support-area">
          <!-- single support -->
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="aa-support-single">
                <ul class="social-network social-circle">
                    <!-- <li><a href="#" class="icoRss social-circle-a" title="Rss"><i class="fa fa-rss"></i></a></li> --> -->
                    <li><a href="#" class="icoFacebook social-circle-a" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" class="icoTwitter social-circle-a" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" class="icoGoogle social-circle-a" title="Google +"><i class="fa fa-instagram"></i></a></li>
                    <!-- <li><a href="#" class="icoLinkedin social-circle-a" title="Linkedin"><i class="fa fa-linkedin"></i></a></li> -->
                </ul>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="aa-support-single aa-support-service">
                <p>+91 819007 1086</p>
                <p>support@virtuallib.com</p>
                <p>Crafted with <i class="fa fa-heart tealincolor"></i> by awesome people at kitabiworm </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<footer id='aa-footer'>
  <div class="aa-footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-footer-bottom-area">
            <p>COPYRIGHT @ KITABIWORM | ALL RIGHTS RESERVED</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>



<!-- <footer id="aa-footer"> -->
  <!-- footer bottom -->
  <!-- <div class="aa-footer-top">
   <div class="container">
      <div class="row">
      <div class="col-md-12">
        <div class="aa-footer-top-area">
          <div class="row">
            <div class="col-md-4">
              <div class="aa-footer-widget">
                <ul class="social-network social-circle"> -->
                    <!-- <li><a href="#" class="icoRss social-circle-a" title="Rss"><i class="fa fa-rss"></i></a></li> -->
                    <!-- <li><a href="#" class="icoFacebook social-circle-a" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" class="icoTwitter social-circle-a" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" class="icoGoogle social-circle-a" title="Google +"><i class="fa fa-instagram"></i></a></li> -->
                    <!-- <li><a href="#" class="icoLinkedin social-circle-a" title="Linkedin"><i class="fa fa-linkedin"></i></a></li> -->
                <!-- </ul>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 col-offset-md-4">
              <div class="aa-footer-widget">
                <p>+91 819007 1086</p>
                <p>support@virtuallib.com</p>
                <p>Crafted with <i class="fa fa-heart tealincolor"></i> by awesome people at kitabiworm </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   </div>
  </div> -->
  <!-- footer-bottom -->
  <!-- <div class="aa-footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-footer-bottom-area">
            <p>COPYRIGHT @ KITABIWORM | ALL RIGHTS RESERVED</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer> -->
<!-- / footer -->

app/views/shared/_header.html.erb
<!-- Start header section -->
  <header id="aa-header">
    <%= render 'shared/top-header' %>
    <%= render 'shared/bottom-header' %>
  </header>

app/views/shared/_menu.html.erb
<!-- menu -->
<section id="menu">
  <div class="container">
    <div class="menu-area">
      <!-- Navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse">
          <!-- Left nav -->
          <ul class="nav navbar-nav">
            <li><a href="/", class="fa fa-home"></a></li>
            <li><a href="#">How it works</a></li>
            <li><a href="/plans">Membership Plans</a></li>
            <li><a href="/pages/share_earn">Share and Earn</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">About Us</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
</section>
<!-- / menu -->

app/views/shared/_subscribe.html.erb
<!-- Subscribe section -->
<section id="aa-subscribe">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="aa-subscribe-area">
          <h3>Subscribe our newsletter </h3>
          <p>Stay up-to-date with our new book launches, expansions and promotions.</p>
          <%= form_tag subscribers_path, method: :post, class: "aa-subscribe-form" do %>
            <%= email_field_tag :email, params[:email], placeholder:"Enter your Email" %>
            <%= submit_tag "Subscribe" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- / Subscribe section -->

app/views/shared/_support.html.erb
<section id="aa-support">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="aa-support-area">
          <!-- single support -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="aa-support-single">
              <span class="fa fa-motorcycle"></span>
              <h4>FREE DELIVERY</h4>
              <P>We deliever you the books, without any delivery charges.</P>
            </div>
          </div>
          <!-- single support -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="aa-support-single">
              <span class="fa fa-motorcycle fa-flip-horizontal"></span>
              <h4>FREE PICKUP</h4>
              <P>No worries, while returning also. We have free pickup for you.</P>
            </div>
          </div>
          <!-- single support -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="aa-support-single">
              <span class="fa fa-phone"></span>
              <h4>SUPPORT 24/7</h4>
              <P>24x7 Available at your serivce @ support@kitabiworm.com</P>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_top-header.html.erb
<!-- start header top  -->
<div class="aa-header-top">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="aa-header-top-area">
          <!-- start header top left -->
          <div class="aa-header-top-left">
            <div class="cellphone hidden-xs">
              <p><span class="fa fa-phone tealincolor"></span>+91 819007 1086</p>
            </div>
            <div class="cellphone hidden-xs">
              <p>
                <span class="fa fa-envelope tealincolor"></span>
                support@kitabiworm.com
              </p>
            </div>
            <!-- / cellphone -->
          </div>
          <!-- / header top left -->
          <div class="aa-header-top-right">
            <% if user_signed_in? %>
              <ul class="aa-head-top-nav-right-signed-in">
                <% @user_info = current_user.user_info %>
                <% if @user_info.present? %>
                  <li>
                    <%= link_to user_info_path(@user_info), "data-toggle": "tooltip", "data-placement":"bottom", title: 'My Avatar' do %>
                      Hi <span> <%= current_user.name %> </span><i class="fa fa-user tealincolor"></i>
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to new_user_info_path, "data-toggle": "tooltip", "data-placement":"bottom", title: 'My Avatar' do %>
                      Hi <span> <%= current_user.name %> </span><i class="fa fa-user tealincolor"></i>
                    <% end %>
                  </li>
                <% end %>
                <li>
                  <%= link_to bookmarks_path, "data-toggle": "tooltip", "data-placement":"bottom", title: 'My Bookmarks' do %>
                    My Bookmarks <i class="fa fa-bookmark tealincolor medium-size-icons"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to carts_path, "data-toggle": "tooltip", "data-placement":"bottom", title: 'My Cart' do %>
                    My Cart <i class="fa fa-shopping-cart tealincolor medium-size-icons"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to orders_path, "data-toggle": "tooltip", "data-placement":"bottom", title: 'My Orders' do %>
                    My Orders <i class="fa fa-book tealincolor medium-size-icons"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to orders_path, "data-toggle": "tooltip", "data-placement":"bottom", title: 'My Orders' do %>
                    My Wallet <i class="fa fa-credit-card tealincolor medium-size-icons" aria-hidden="true"></i>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, "data-toggle": "tooltip", "data-placement":"bottom", title: 'Sign Out', method: :delete  do %>
                    Sign Out <i class="fa fa-sign-out tealincolor medium-size-icons"></i>
                  <% end %>
                </li>
              </ul>
            <% else %>
              <ul class="aa-head-top-nav-right">
                <li>
                  <%= link_to new_user_session_path, class:"fa fa-sign-in" do %>
                      <span class="link_to_font">Log In</span>
                  <% end %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- / header top  -->