config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :bookmarks, only: [:destroy, :index]
  resources :subscribers, only: [:create, :new]
  resources :user_infos
  resources :publications
  resources :authors
  resources :carts
  resources :plans
  resources :addresses, only: [:new, :edit, :destroy]
  devise_for :users
  root to: 'books#home'
  resources :books do
    resources :carts
    resources :book_catalogs
    resources :bookmarks, only: [:create]
  end
  resources :carts do
    resources :orders, except: [:index, :show, :edit]
  end
  resources :orders, only: [:index, :show, :edit]
  resources :plans, only: [:index]

  post "/plans/:sub_plan_id/select_plan" => "plans#select_plan", as: 'select_plan'
  post "/plans/:sub_plan_id/change_plan" => "plans#change_plan", as: 'change_plan'
  # get "/books/:book_id/book_catalogs/new" => "book_catalogs#new", :as => 'new_book_catalog'
  # post "/books/:book_id/book_catalogs" =>	"book_catalogs#create", :as => 'create_book_catalog'
  post "/books/:id/check_pincode" => "books#check_pincode", as: 'check_pincode'
  get  "/" => "books#home", :as => 'home'
  get  "pages/:page" => "pages#show"

  delete "/cart_books/:id" => "carts#destroy_cart_book", as: 'destroy_cart_book'
  get "/checkout/:cart_id" => "orders#checkout", as: 'order_checkout'

  get "/shipping_address" => "orders#select_shipping_address", as: 'select_shipping_address'
  post "/order_summary" => "orders#summary", as: 'order_summary'
  post "/cancel_order/:id" => "orders#cancel", as: 'cancel_order'
  post "/order/:order_id/return_requests" => "return_requests#create", as: 'return_request'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_books, dependent: :destroy
  has_one :order
  belongs_to :user

  # Status 1 represents that cart has been successfully converted into order.
  # Status 0 represents that cart is still in pending process.


  def self.active
    find_by(status: 0)
  end

  def self.update_cart(values = {})
    book = Book.find(values[:book_id])
    user = User.find(values[:user_id])
    c = Cart.find_by(status: 0, user_id: user.id)
    if c.nil?
      cart = Cart.create(
          user_id: user.id,
          value: book.rent_price,
          status: 0
        )
      CartBook.create(
        cart_id: cart.id, book_id: book.id, price: book.rent_price
      )
      return cart
    else
      CartBook.create(
        cart_id: c.id, book_id: values[:book_id], price: book.rent_price
      )
      total_cart_value = Cart.total_value(c.id)
      c.update(value: total_cart_value)
      return c
    end
  end

  # Calculates total cart value.
  def self.total_value(cart_id)
    CartBook.where(cart_id: cart_id).sum(:price)
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_signin
  before_action :set_book, only: [:create]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :check_membership, only: [:new, :create, :edit, :update]
  before_action :set_cart_book, only: [:destroy_cart_book]

  # before_action :check_book_price, only: [:new, :create, :edit, :update]

  # GET /carts
  # GET /carts.json
  def index
    @cart = current_user.carts.active
    @cart_books = @cart.cart_books if @cart.present?
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = current_user.carts.active
    @cart_books = @cart.cart_books if @cart.present?
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.update_cart({book_id: @book.id, user_id: current_user.id})
    respond_to do |format|
      format.html {redirect_to @cart, notice: "You have successfully added #{@book.name} to cart."}
      # if @cart.save
      #   format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
      #   format.json { render :show, status: :created, location: @cart }
      # else
      #   format.html { render :new }
      #   format.json { render json: @cart.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_cart_book
    @book_name = @cart_book.book.name
    @cart_book.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "#{@book_name} was successfully removed from cart." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def check_signin
      if !user_signed_in?
        respond_to do |format|
          format.html{
            redirect_to new_user_session_path, notice: t('signin_message')
          }
        end
      end
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    def set_cart
      @cart = Cart.find(params[:id])
    end

    def set_cart_book
      @cart_book = CartBook.find(params[:id])
    end

    def check_membership
      if current_user.sub_plan.nil?
        respond_to do |format|
          format.html {
            redirect_to plans_url, notice: t('carts.check_membership.no_membership')
          }
        end
      elsif current_user.membership_expired?
        respond_to do |format|
          format.html {
            redirect_to plans_url, notice: t('carts.check_membership.membership_expired')
          }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id, :book_id, :value)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online Book Store | Home</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'> -->

  </head>
  <body>
   <!-- wpf loader Two -->
    <!-- <div id="wpf-loader-two">
      <div class="wpf-loader-two-inner">
        <span>Loading</span>
      </div>
    </div> -->
    <!-- / wpf loader Two -->
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->
  <!-- Start header section -->
    <%= render 'shared/header' %>
  <!-- End of header section -->
  <!-- Start of menu section -->
    <%= render 'shared/menu' %>
  <!-- End of menu section -->
    <!-- catg header banner section -->
    <!-- <section id="aa-catg-head-banner">
     <img src="images/library.jpg" alt="fashion img">
     <div class="aa-catg-head-banner-area">
       <div class="container">
        <div class="aa-catg-head-banner-content">
          <h2>Cart Page</h2>
          <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Cart</li>
          </ol>
        </div>
       </div>
     </div>
    </section> -->
    <!-- / catg header banner section -->
   <% if @cart.present? %>
     <!-- Cart view section -->
     <section id="cart-view">
       <div class="container">
         <div class="row">
           <div class="col-md-12">
             <div class="cart-view-area">
               <div class="cart-view-table">
                 <form action="">
                   <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr>
                            <th></th>
                            <th></th>
                            <th>Book</th>
                            <th>Price</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% @cart_books.each do |cart_book| %>
                            <tr>
                              <td>
                                <%= link_to destroy_cart_book_path(cart_book), method: :delete, data: { confirm: 'Are you sure?' }, class:'remove' do %>
                                  <fa class="fa fa-close"></fa>
                                <% end %>
                              </td>
                              <td>
                                <a href="#">
                                  <%= image_tag(cart_book.book.front_image, alt: "#{cart_book.book.name} image") %>
                                </a>
                              </td>
                              <td>
                                <a class="aa-cart-title" href="#">
                                  <%= cart_book.book.name %>
                                </a> by <%= cart_book.book.author_name %>
                              </td>
                              <td>₹ <%= cart_book.price %></td>
                              <!-- <td><input class="aa-cart-quantity" type="number" value="1"></td> -->
                              <!-- <td>$250</td> -->
                            </tr>
                          <% end %>
                          <tr>
                            <td colspan="6" class="aa-cart-view-bottom">
                              <%= link_to 'Continue renting more books', books_url, class: 'aa-browse-btn' %>
                            </td>
                          </tr>
                          </tbody>
                      </table>
                    </div>
                 </form>
                 <!-- Cart Total view -->
                 <div class="cart-view-total">
                   <h4>Cart Totals</h4>
                   <table class="aa-totals-table">
                     <tbody>
                       <tr>
                         <th>Subtotal</th>
                         <td>₹ <%= @cart.value %></td>
                       </tr>
                       <tr>
                         <th>Total</th>
                         <td>₹ <%= @cart.value %></td>
                       </tr>
                       <tr>
                         <th>Amount to be paid</th>
                         <td>₹ <%= current_user.wallet.amount_to_be_paid(@cart.value) %></td>
                       </tr>
                     </tbody>
                   </table>
                   <%= link_to 'Proced to Checkout', select_shipping_address_path, class: 'aa-browse-btn'  %>
                 </div>
               </div>
             </div>
           </div>
         </div>
       </div>
     </section>
    <% else %>
    <section id="cart-view">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="aa-empty-cart-area">
              <h2 class="aa-empty-cart"> Your shopping <i class="fa fa-shopping-cart"></i> is empty ! </h3>
            </div>
          </div>
        </div>
      </div>
    </section>
    <% end %>
   <!-- / Cart view section -->
<%= render 'shared/support' %>
<%= render 'shared/subscribe' %>
<%= render 'shared/footer' %>

app/views/carts/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online Book Store | Home</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <!-- <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'> -->

  </head>
  <body>
   <!-- wpf loader Two -->
    <!-- <div id="wpf-loader-two">
      <div class="wpf-loader-two-inner">
        <span>Loading</span>
      </div>
    </div> -->
    <!-- / wpf loader Two -->
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->
  <!-- Start header section -->
    <%= render 'shared/header' %>
  <!-- End of header section -->
  <!-- Start of menu section -->
    <%= render 'shared/menu' %>
  <!-- End of menu section -->
    <!-- catg header banner section -->
    <!-- <section id="aa-catg-head-banner">

     <div class="aa-catg-head-banner-area">
       <div class="container">
        <div class="aa-catg-head-banner-content">
          <h2>Cart Page</h2>
          <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Cart</li>
          </ol>
        </div>
       </div>
     </div>
    </section> -->
    <!-- / catg header banner section -->

   <!-- Cart view section -->
   <section id="cart-view">
     <div class="container">
       <div class="row">
         <div class="col-md-12">
           <div class="cart-view-area">
             <div class="cart-view-table">
                 <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th></th>
                          <th></th>
                          <th>Book</th>
                          <th>Price</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% @cart_books.each do |cart_book| %>
                          <tr>
                            <td>
                              <%= link_to destroy_cart_book_path(cart_book), method: :delete, data: { confirm: 'Are you sure?' }, class:'remove' do %>
                                <fa class="fa fa-close"></fa>
                              <% end %>
                            </td>
                            <td>
                              <%= image_tag(cart_book.book.front_image, alt: "#{cart_book.book.name} image") %>
                            </td>
                            <td>
                              <%= link_to cart_book.book, class: 'aa-cart-title' do %>
                                <%= cart_book.book.name %> by <%= cart_book.book.author_name %>
                              <% end %>
                            </td>
                            <td>₹ <%= cart_book.price %></td>
                            <!-- <td><input class="aa-cart-quantity" type="number" value="1"></td> -->
                            <!-- <td>$250</td> -->
                          </tr>
                        <% end %>
                        <tr>
                          <td colspan="6" class="aa-cart-view-bottom">
                            <%= link_to 'Continue renting more books', books_url, class: 'aa-browse-btn' %>
                          </td>
                        </tr>
                        </tbody>
                    </table>
                  </div>
               <!-- Cart Total view -->
               <div class="cart-view-total">
                 <h4>Cart Totals</h4>
                 <table class="aa-totals-table">
                   <tbody>
                     <tr>
                       <th>Subtotal</th>
                       <td>₹ <%= @cart.value %></td>
                     </tr>
                     <tr>
                       <th>Total</th>
                       <td>₹ <%= @cart.value %></td>
                     </tr>
                     <tr>
                       <th>Amount to be paid</th>
                       <td>₹ <%= current_user.wallet.amount_to_be_paid(@cart.value) %></td>
                     </tr>
                   </tbody>
                 </table>
                 <%= link_to 'Proced to Checkout', select_shipping_address_path, class: 'aa-browse-btn'  %>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </section>
   <!-- / Cart view section -->
<%= render 'shared/support' %>
<%= render 'shared/subscribe' %>
<%= render 'shared/footer' %>