config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :bookmarks, only: [:destroy, :index]
  resources :subscribers, only: [:create, :new]
  resources :user_infos
  resources :publications
  resources :authors
  resources :carts
  resources :plans
  resources :addresses, only: [:new, :edit, :destroy]
  devise_for :users
  root to: 'books#home'
  resources :books do
    resources :carts
    resources :book_catalogs
    resources :bookmarks, only: [:create]
  end
  resources :carts do
    resources :orders, except: [:index, :show, :edit]
  end
  resources :orders, only: [:index, :show, :edit]
  resources :plans, only: [:index]

  post "/plans/:sub_plan_id/select_plan" => "plans#select_plan", as: 'select_plan'
  post "/plans/:sub_plan_id/change_plan" => "plans#change_plan", as: 'change_plan'
  # get "/books/:book_id/book_catalogs/new" => "book_catalogs#new", :as => 'new_book_catalog'
  # post "/books/:book_id/book_catalogs" =>	"book_catalogs#create", :as => 'create_book_catalog'
  post "/books/:id/check_pincode" => "books#check_pincode", as: 'check_pincode'
  get  "/" => "books#home", :as => 'home'
  get  "pages/:page" => "pages#show"

  delete "/cart_books/:id" => "carts#destroy_cart_book", as: 'destroy_cart_book'
  get "/checkout/:cart_id" => "orders#checkout", as: 'order_checkout'

  get "/shipping_address" => "orders#select_shipping_address", as: 'select_shipping_address'
  post "/order_summary" => "orders#summary", as: 'order_summary'
  post "/cancel_order/:id" => "orders#cancel", as: 'cancel_order'
  post "/order/:order_id/return_requests" => "return_requests#create", as: 'return_request'
end

app/models/book_catalog.rb
class BookCatalog < ApplicationRecord
  belongs_to :book
  mount_uploader :catalog, CatalogUploader

end

app/controllers/book_catalogs_controller.rb
class BookCatalogsController < ApplicationController
  before_action :set_book_catalog, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:index, :new]

  # GET /book_catalogs
  # GET /book_catalogs.json
  def index
    @book_catalogs = @book.book_catalogs
  end

  # GET /book_catalogs/1
  # GET /book_catalogs/1.json
  def show
  end

  # GET /book_catalogs/new
  def new
    @book_catalog = BookCatalog.new
  end

  # GET /book_catalogs/1/edit
  def edit
  end

  # POST /book_catalogs
  # POST /book_catalogs.json
  def create
    @book_catalog = BookCatalog.new(book_catalog_params)

    respond_to do |format|
      if @book_catalog.save
        format.html { redirect_to @book_catalog, notice: 'Book catalog was successfully created.' }
        format.json { render :show, status: :created, location: @book_catalog }
      else
        format.html { render :new }
        format.json { render json: @book_catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_catalogs/1
  # PATCH/PUT /book_catalogs/1.json
  def update
    respond_to do |format|
      if @book_catalog.update(book_catalog_params)
        format.html { redirect_to @book_catalog, notice: 'Book catalog was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_catalog }
      else
        format.html { render :edit }
        format.json { render json: @book_catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_catalogs/1
  # DELETE /book_catalogs/1.json
  def destroy
    @book_catalog.destroy
    respond_to do |format|
      format.html { redirect_to book_catalogs_url, notice: 'Book catalog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_catalog
      @book_catalog = BookCatalog.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_catalog_params
      params.require(:book_catalog).permit(:book_id, :catalog)
    end
end

app/helpers/book_catalogs_helper.rb
module BookCatalogsHelper
end

app/views/book_catalogs/edit.html.erb
<h1>Editing Book Catalog</h1>

<%= render 'form', book_catalog: @book_catalog %>

<%= link_to 'Show', @book_catalog %> |
<%= link_to 'Back', book_catalogs_path %>

app/views/book_catalogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Catalogs</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Catalog</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_catalogs.each do |book_catalog| %>
      <tr>
        <td><%= book_catalog.book_id %></td>
        <td><%= book_catalog.catalog %></td>
        <td><%= link_to 'Show', book_catalog %></td>
        <td><%= link_to 'Edit', edit_book_catalog_path(book_catalog) %></td>
        <td><%= link_to 'Destroy', book_catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Catalog', new_book_catalog_path(@book) %>

app/views/book_catalogs/new.html.erb
<h1>New Book Catalog</h1>

<%= form_tag( url: create_book_catalog_path(@book), method: :post ) do  %>
  <%= label_tag :catalog %>
  <%= file_field_tag :catalog, multipart: true %>

  <%= submit_tag "Upload", class: "btn btn-large btn-primary" %>
<% end %>

app/views/book_catalogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book_catalog.book_id %>
</p>

<p>
  <strong>Catalog:</strong>
  <%= @book_catalog.catalog %>
</p>

<%= link_to 'Edit', edit_book_catalog_path(@book_catalog) %> |
<%= link_to 'Back', book_catalogs_path %>